VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CECB4"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public ID
Public CRGGlobalId
Public CRGOneId
Public CRGCBSId
Public CRGType
Public CRGResp
Public regionCode
Public marketCode
Public marketType
Public countryCode
Public GCUReportingGroupId
Public GCUReportingGroupCode
Public GCUReportingGroupName
Public parentType
Public CUReportingGroupId
Public CUReportingGroupName
Public CRGCode
Public CRGName
Public CUManager
Public comments
Public directMarketController
' 21 total members
' 21 - 1 ID = 20 members
